<?php

namespace AppBundle\Repository;

/**
 * CategoryObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryObjectRepository extends \Doctrine\ORM\EntityRepository
{
}
