<?php

namespace AppBundle\Repository;

/**
 * LobbyPlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LobbyPlayerRepository extends \Doctrine\ORM\EntityRepository
{
}
